github:
  url: https://github.com/apache/dubbo
  start: 10000
  end: 11000
  agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

proxy:
  address: 127.0.0.1
  port: :7890
